### ISSUE TITLE
Uncaught Error: Call to a member function move() 

### ISSUE THREAD

**Issue by dathwa** [afragen/git-updater#1015]
Hi.
Getting this error when trying to activate the plugin.
WP 6.1

```
Warning: Attempt to read property "method" on null in public_html/wp-content/plugins/git-updater-develop/src/Git_Updater/Shim.php on line 45

Warning: Attempt to read property "method" on null in public_html/wp-content/plugins/git-updater-develop/src/Git_Updater/Shim.php on line 52

Fatal error: Uncaught Error: Call to a member function move() on null in public_html/wp-content/plugins/git-updater-develop/src/Git_Updater/Shim.php:53 Stack trace: #0 public_html/wp-content/plugins/git-updater-develop/src/Git_Updater/Bootstrap.php(169): move_dir('/home/virtual/v...', '/home/virtual/v...') #1 public_html/wp-includes/class-wp-hook.php(308): Fragen\Git_Updater\Bootstrap->rename_on_activation('') #2 public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #3 public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 public_html/wp-admin/plugins.php(194): do_action('activate_git-up...') #5 {main} thrown in public_html/wp-content/plugins/git-updater-develop/src/Git_Updater/Shim.php on line 53
```

**Comment by afragen** [comment]
Hmm, I would've thought `$wp_filesystem` was loaded. 

I think I know why.

**Comment by afragen** [comment]
Unless there's some reason you want to be on the develop branch you can download the release version from https://git-updater.com

**Comment by dathwa** [comment]
> Unless there's some reason you want to be on the develop branch you can download the release version from https://git-updater.com

Aha. I Found the link to your plugin on some blog post. Thanks for the correct link.
